---
- hosts: all
  become: true
  gather_facts: false
  vars_files:
    - vars/default.yml

  tasks:
    - name: Add a sample user 'pace'
      user:
        name: pace
        comment: PACE User

    - name: Update and upgrade apt packages
      apt:
        upgrade: yes
        update_cache: yes

    - name: Install Apache
      apt:
        name: apache2
        update_cache: yes
        state: latest

    - name: Create document root
      file:
        path: "/var/www/{{ http_host }}"
        state: directory
        owner: "{{ app_user }}"
        mode: "0755"

    - name: Copy index test page
      template:
        src: "files/index.html.j2"
        dest: "/var/www/{{ http_host }}/index.html"

    - name: Start service httpd, if not started
      service:
        name: apache2
        state: started

    - name: Disable default Apache site
      shell: /usr/sbin/a2dissite 000-default.conf
      when: disable_default
      notify: Reload Apache

  handlers:
    - name: Reload Apache
      service:
        name: apache2
        state: reloaded

    - name: Restart Apache
      service:
        name: apache2
        state: restarted
